#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop comment "early drop of invalid connections"
    ct state {established, related} accept comment "allow tracked connections"
    iif lo accept comment "allow from loopback"
    iifname "docker0" accept comment "allow docker bridge"
    iifname "br-*" accept comment "allow docker compose bridges"
    meta l4proto { icmp, icmpv6 } accept comment "allow icmp"
    tcp dport ssh accept comment "allow sshd"
    tcp dport { 3000, 8000 } accept comment "allow operator core (frontend + backend)"
    pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
  }
  chain forward {
    type filter hook forward priority filter
    policy drop

    ct state {established, related} accept comment "allow tracked forwards"
    iifname "docker0" accept comment "allow docker outbound"
    oifname "docker0" accept comment "allow docker inbound"
    iifname "br-*" accept comment "allow docker compose outbound"
    oifname "br-*" accept comment "allow docker compose inbound"
  }
}
