# ─────────────────────────────────────────────────────────────────────────────
# Autostart — bars, daemons, optional apps
# ─────────────────────────────────────────────────────────────────────────────

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = quickshell
