[General]
Background           = "Backgrounds/background.png"
ScreenWidth          = 1920
ScreenHeight         = 1080
FullBlur             = false
PartialBlur          = true
BlurRadius           = 50
AccentColor          = "#5865F2"
MainColor            = "#f8f8f2"
Font                 = "JetBrains Mono Nerd Font"
FontSize             = "14"
LoginBackground      = true
LoginBackgroundColor = "#0d0d0d"
HeaderText           = ""
FormPosition         = "center"
HaveFormBackground   = false
