-- ─────────────────────────────────────────────────────────────────────────────
-- NvChad — SL1C3D-L4BS | Hyprland #1 brand (white, black, grey, Discord Blurple)
-- Elite 2026: full base_16 + base_30 override, hl_override, Treesitter, NvDash
-- ─────────────────────────────────────────────────────────────────────────────

---@type ChadrcConfig
local M = {}

-- Theme: onedark base, fully overridden with SL1C3D-L4BS palette
M.base46 = {
  theme = "onedark",
  transparency = false,
  hl_add = {},
  hl_override = {
    Comment = { fg = "#909090", italic = true },
    ["@comment"] = { fg = "#909090", italic = true },
    ["@keyword"] = { fg = "#5865F2" },
    ["@keyword.function"] = { fg = "#5865F2" },
    ["@keyword.return"] = { fg = "#5865F2" },
    ["@keyword.import"] = { fg = "#5865F2" },
    ["@function"] = { fg = "#5865F2" },
    ["@function.call"] = { fg = "#5865F2" },
    ["@function.builtin"] = { fg = "#b366ff" },
    ["@method"] = { fg = "#5865F2" },
    ["@method.call"] = { fg = "#5865F2" },
    ["@type"] = { fg = "#e0e0e0", bold = true },
    ["@type.builtin"] = { fg = "#e0e0e0" },
    ["@string"] = { fg = "#50fa7b" },
    ["@string.escape"] = { fg = "#b366ff" },
    ["@number"] = { fg = "#f1fa8c" },
    ["@float"] = { fg = "#f1fa8c" },
    ["@boolean"] = { fg = "#5865F2" },
    ["@operator"] = { fg = "#f8f8f2" },
    ["@variable"] = { fg = "#f8f8f2" },
    ["@variable.builtin"] = { fg = "#b366ff", italic = true },
    ["@parameter"] = { fg = "#e0e0e0" },
    ["@field"] = { fg = "#e0e0e0" },
    ["@property"] = { fg = "#e0e0e0" },
    ["@tag"] = { fg = "#5865F2" },
    ["@tag.attribute"] = { fg = "#e0e0e0" },
    ["@tag.delimiter"] = { fg = "#909090" },
    ["@error"] = { fg = "#ff5555" },
    ["@exception"] = { fg = "#ff5555" },
    ["@punctuation.bracket"] = { fg = "#909090" },
    ["@punctuation.delimiter"] = { fg = "#909090" },
    Normal = { fg = "#f8f8f2", bg = "#0d0d0d" },
    NormalFloat = { bg = "#1a1a1a" },
    FloatBorder = { fg = "#2d2d2d", bg = "#1a1a1a" },
    StatusLine = { fg = "#e0e0e0", bg = "#1a1a1a" },
    CursorLine = { bg = "#1a1a1a" },
    CursorLineNr = { fg = "#5865F2", bold = true },
    LineNr = { fg = "#404040" },
    Pmenu = { fg = "#f8f8f2", bg = "#1a1a1a" },
    PmenuSel = { fg = "#f8f8f2", bg = "#5865F2" },
    PmenuBorder = { fg = "#2d2d2d" },
    NvimTreeFolderIcon = { fg = "#5865F2" },
    NvimTreeFolderName = { fg = "#5865F2" },
    NvimTreeOpenedFolderName = { fg = "#b366ff" },
    TelescopeBorder = { fg = "#2d2d2d", bg = "#0d0d0d" },
    TelescopeSelection = { fg = "#f8f8f2", bg = "#5865F2" },
    TelescopeSelectionCaret = { fg = "#b366ff" },
    TelescopeMatching = { fg = "#b366ff", bold = true },
    TelescopePromptBorder = { fg = "#5865F2" },
    WinSeparator = { fg = "#2d2d2d" },
    TabLine = { fg = "#909090", bg = "#1a1a1a" },
    TabLineFill = { bg = "#0d0d0d" },
    TabLineSel = { fg = "#f8f8f2", bg = "#5865F2", bold = true },
    FloatTitle = { fg = "#b366ff", bg = "#1a1a1a", bold = true },
    -- IblIndent / indent-blankline
    IblIndent = { fg = "#2d2d2d" },
    IblScope = { fg = "#5865F2" },
    -- Noice
    NoiceCmdlinePopupBorder = { fg = "#5865F2" },
    NoiceCmdlinePopupTitle = { fg = "#b366ff" },
    -- Gitsigns
    GitSignsAdd = { fg = "#50fa7b" },
    GitSignsChange = { fg = "#5865F2" },
    GitSignsDelete = { fg = "#ff5555" },
  },
  changed_themes = {
    onedark = {
      base_16 = {
        base00 = "#0d0d0d",
        base01 = "#1a1a1a",
        base02 = "#2d2d2d",
        base03 = "#909090",
        base04 = "#909090",
        base05 = "#f8f8f2",
        base06 = "#e0e0e0",
        base07 = "#1a1a1a",
        base08 = "#ff5555",
        base09 = "#f1fa8c",
        base0A = "#f1fa8c",
        base0B = "#50fa7b",
        base0C = "#e0e0e0",
        base0D = "#5865F2",
        base0E = "#b366ff",
        base0F = "#909090",
      },
      base_30 = {
        black = "#0d0d0d",
        darker_black = "#080808",
        black2 = "#1a1a1a",
        one_bg = "#1a1a1a",
        one_bg2 = "#2d2d2d",
        one_bg3 = "#404040",
        grey = "#909090",
        grey_fg = "#909090",
        grey_fg2 = "#6c6c6c",
        light_grey = "#e0e0e0",
        line = "#2d2d2d",
        white = "#f8f8f2",
        statusline_bg = "#1a1a1a",
        lightbg = "#1a1a1a",
        lightbg2 = "#2d2d2d",
        pmenu_bg = "#5865F2",
        folder_bg = "#5865F2",
        blue = "#5865F2",
        nord_blue = "#5865F2",
        purple = "#b366ff",
        dark_purple = "#5865F2",
        red = "#ff5555",
        baby_pink = "#ff79c6",
        pink = "#ff79c6",
        green = "#50fa7b",
        vibrant_green = "#50fa7b",
        yellow = "#f1fa8c",
        sun = "#f1fa8c",
        orange = "#ffb86c",
        cyan = "#e0e0e0",
        teal = "#50fa7b",
      },
    },
  },
  integrations = {},
}

-- UI: statusline, tabufline, cmp, telescope
M.ui = {
  statusline = {
    enabled = true,
    theme = "default",
    separator_style = "round",
  },
  tabufline = {
    enabled = true,
    lazyload = true,
  },
  telescope = { style = "borderless" },
  cmp = {
    style = "default",
    icons_left = true,
  },
}

-- NvDash: branded startup screen
M.nvdash = {
  load_on_startup = true,
  header = {
    "                                                        ",
    "  ███████╗██╗     ██╗ ██████╗██████╗ ██████╗          ",
    "  ██╔════╝██║    ███║██╔════╝╚════██╗██╔══██╗         ",
    "  ███████╗██║    ╚██║██║      █████╔╝██║  ██║         ",
    "  ╚════██║██║     ██║██║     ██╔═══╝ ██║  ██║         ",
    "  ███████║███████╗██║╚██████╗███████╗██████╔╝         ",
    "  ╚══════╝╚══════╝╚═╝ ╚═════╝╚══════╝╚═════╝          ",
    "          ██╗      ██╗  ██╗██████╗ ███████╗           ",
    "          ██║      ██║  ██║██╔══██╗██╔════╝           ",
    "          ██║█████╗███████║██████╔╝███████╗           ",
    "          ██║╚════╝╚════██║██╔══██╗╚════██║           ",
    "          ███████╗      ██║██████╔╝███████║           ",
    "          ╚══════╝      ╚═╝╚═════╝ ╚══════╝           ",
    "                                                        ",
    "            E L I T E  ·  2 0 2 6  ·  A R C H         ",
    "                                                        ",
  },
  buttons = {
    { txt = "  Find File",      keys = "Spc f f", cmd = "Telescope find_files" },
    { txt = "  Recent Files",   keys = "Spc f o", cmd = "Telescope oldfiles" },
    { txt = "󰈭  Find Word",      keys = "Spc f w", cmd = "Telescope live_grep" },
    { txt = "  Bookmarks",      keys = "Spc m a", cmd = "Telescope marks" },
    { txt = "  Config",         keys = "Spc e e", cmd = "e $MYVIMRC" },
    { txt = "  Lazy",           keys = "Spc l l", cmd = "Lazy" },
    { txt = "  Quit",           keys = "Spc q",   cmd = "qa" },
  },
}

return M
